// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next, data }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please set these in your .env file.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }
    
    const request = getRequest();

    if (!request?.headers) {
      console.error('[Auth] No request headers available');
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    // Try to get token from Authorization header first
    const authHeader = request.headers.get('authorization');
    let token: string | null = null;
    let authMethod: string = '';

    if (authHeader) {
      if (!authHeader.startsWith('Bearer ')) {
        console.error('[Auth] Invalid authorization header format:', authHeader.substring(0, 20));
        throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
      }
      token = authHeader.replace('Bearer ', '');
      authMethod = 'header';
    } else {
      // Fallback: check for token in request body
      const bodyToken = (data as any)?.__auth_token;
      if (bodyToken && typeof bodyToken === 'string') {
        token = bodyToken;
        authMethod = 'body';
      }
    }

    if (!token) {
      console.error('[Auth] No authorization token provided (checked header and body)');
      throw new Response('Unauthorized: No authorization token provided', { status: 401 });
    }

    console.log(`[Auth] Using token from ${authMethod}`);

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data: claimsData, error } = await supabase.auth.getClaims(token);
    if (error || !claimsData?.claims) {
      console.error('[Auth] Invalid token or claims:', error?.message);
      throw new Response('Unauthorized: Invalid token', { status: 401 });
    }

    if (!claimsData.claims.sub) {
      console.error('[Auth] No user ID in token claims');
      throw new Response('Unauthorized: No user ID found in token', { status: 401 });
    }

    console.log('[Auth] Success - User ID:', claimsData.claims.sub);

    return next({
      context: {
        supabase,
        userId: claimsData.claims.sub,
        claims: claimsData.claims,
      },
    })
  }
)
