/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as ApiPublicAgentTickRouteImport } from './routes/api/public/agent-tick'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentTickRoute = ApiPublicAgentTickRouteImport.update({
  id: '/api/public/agent-tick',
  path: '/api/public/agent-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/ask': typeof AskRoute
  '/login': typeof LoginRoute
  '/timeline': typeof TimelineRoute
  '/category/$slug': typeof CategorySlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/ask': typeof AskRoute
  '/login': typeof LoginRoute
  '/timeline': typeof TimelineRoute
  '/category/$slug': typeof CategorySlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/ask': typeof AskRoute
  '/login': typeof LoginRoute
  '/timeline': typeof TimelineRoute
  '/category/$slug': typeof CategorySlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/api/public/agent-tick': typeof ApiPublicAgentTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/ask'
    | '/login'
    | '/timeline'
    | '/category/$slug'
    | '/post/$slug'
    | '/api/public/agent-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/ask'
    | '/login'
    | '/timeline'
    | '/category/$slug'
    | '/post/$slug'
    | '/api/public/agent-tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/ask'
    | '/login'
    | '/timeline'
    | '/category/$slug'
    | '/post/$slug'
    | '/api/public/agent-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AskRoute: typeof AskRoute
  LoginRoute: typeof LoginRoute
  TimelineRoute: typeof TimelineRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PostSlugRoute: typeof PostSlugRoute
  ApiPublicAgentTickRoute: typeof ApiPublicAgentTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-tick': {
      id: '/api/public/agent-tick'
      path: '/api/public/agent-tick'
      fullPath: '/api/public/agent-tick'
      preLoaderRoute: typeof ApiPublicAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AskRoute: AskRoute,
  LoginRoute: LoginRoute,
  TimelineRoute: TimelineRoute,
  CategorySlugRoute: CategorySlugRoute,
  PostSlugRoute: PostSlugRoute,
  ApiPublicAgentTickRoute: ApiPublicAgentTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
